---
title: "Schedule"
format: 
  html:
    code-fold: false
    code-tools: false
editor: visual
---

::: {.callout-note appearance="minimal"}
## Day 1: 22nd July 2024

## **Introduction to Health Technology Assessment**

**Objective:** Understanding the building blocks of HTA & its potential in Kenya

**Session Chair:**  [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech)
:::

| Time          | Topic                                                                                                                                    | Type      | Presenter                                                                             |
|-----------------|-----------------|-----------------|----------------------|
| 08:00 - 08:30 | Arrival and registration                                                                                                                 |           |                                                                                       |
| 08:30 - 08:50 | Introductions and welcoming remarks                                                                                                      |           | [Daniel Mwai](https://economics.uonbi.ac.ke/staff/dr-daniel-ngugi-mwai)               |
| 08:50 - 09:00 | [Goals, objectives and structure of the training](https://drive.google.com/file/d/1kpGaI1JkMqZ9YKxEQY6SJzTHzRgYEx6v/view?usp=share_link) |           | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech) |
| 09:00 - 10:30 | [Introduction to HTA](https://drive.google.com/file/d/1ZZRgN-sDohlQEnqR7HEv9xzaMQsQJdA1/view?usp=share_link)                             | Lecture   | [Saudamini Dabak](https://www.hitap.net/en/staff/170776)                              |
| 10:30 - 11:00 | ☕ Tea break                                                                                                                             |           |                                                                                       |
| 11:00 - 12:00 | Case studies of HTA in health decision-making                                                                                            |           | [Panchanok Muenkaew](https://www.hitap.net/en/staff/189371)                           |
| 12:00 - 12:40 | Infrastructure for HTA: Where are we in Kenya?                                                                                           | Lecture   | [Daniel Mwai](https://economics.uonbi.ac.ke/staff/dr-daniel-ngugi-mwai)               |
| 12:40 - 14:00 | 🍲 Lunch break                                                                                                                           |           |                                                                                       |
| 14:00 - 15:00 | [Topic nomination](https://drive.google.com/file/d/1L9kZ8iwt-KQrlxNh2M2AcbNhZV0ELtAV/view?usp=share_link)                                | Practical | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech) |
| 15:00 - 16:00 | Group Feedback                                                                                                                           | Plenary   | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech) |
| 16:00 - 16:30 | ☕ Tea break                                                                                                                             |           |                                                                                       |
|               | [Further reading](https://drive.google.com/drive/folders/1z_BZuzHJUZMbU6tRjDzn2S4V7_mEaua4?usp=share_link)                               |           |                                                                                       |

::: {.callout-note appearance="minimal"}
## Day 2: 23rd July 2024

## **Epidemiological Methods in HTA**

**Objective:** Understanding how epidemiology research can serve HTA

**Session Chair:** [Jeanette Dawa](https://cema-africa.uonbi.ac.ke/people/secretariat/dr-jeanette-dawa)
:::

| Time          | Topic                                                                                                                                                                          | Type      | Presenter                                                                                        |
|-----------------|-----------------|-----------------|----------------------|
| 08:30 - 09:00 | [Epidemiology key concepts I (Introduction to epidemiology)](https://drive.google.com/file/d/1SGjMbr9kJNAG2k0Nsfn1H60-cvRLD8ZG/view?usp=share_link)                            | Lecture   | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech)            |
| 09:00 - 10:30 | [Epidemiology key concepts II (Study design and measures of disease)](https://drive.google.com/file/d/14Nnf5IvBd5pdH9mxWFWK0aMJ1kosMjlJ/view?usp=share_link)                   | Lecture   | [Jeanette Dawa](https://cema-africa.uonbi.ac.ke/people/secretariat/dr-jeanette-dawa)             |
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                                                   |           |                                                                                                  |
| 11:00 - 11:45 | [Epidemiology key concepts III (Causal concepts)](https://drive.google.com/file/d/1wmpoFgptF99-wmXGxyo8c_pqC4EXQukp/view?usp=share_link)                                       | Lecture   | [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi)          |
| 11:45 - 12:15 | [The role of Epidemiology in HTA decisions](https://drive.google.com/file/d/1BOfIdFwqoERDMeeJ5596mR17FVcImF_R/view?usp=share_link)                                             | Lecture   | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech)            |
| 12:15 - 12:45 | [Literature search for existing evidence](https://drive.google.com/file/d/1egq8eZ8a3Y-SAR80oKxrwXwzLPVzyYkA/view?usp=share_link)                                               | Lecture   | [Jeanette Dawa](https://cema-africa.uonbi.ac.ke/people/secretariat/dr-jeanette-dawa)             |
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                                                 |           |                                                                                                  |
| 14:00 - 14:30 | [Literature search for existing evidence](https://drive.google.com/file/d/1egq8eZ8a3Y-SAR80oKxrwXwzLPVzyYkA/view?usp=share_link)                                               | Lecture   | [Jeanette Dawa](https://cema-africa.uonbi.ac.ke/people/secretariat/dr-jeanette-dawa)             |
| 14:30 - 15:30 | [Critical appraisal of literature](https://docs.google.com/presentation/d/1QERij7JiWE2tdM6eN7cEdY7eYsgV6oP5/edit?usp=share_link&ouid=113648051799093918679&rtpof=true&sd=true) | Lecture   | [Marybeth Maritim](https://cema-africa.uonbi.ac.ke/people/clinical-research/dr-marybeth-maritim) |
| 15:30 - 15:45 | ☕ Tea break                                                                                                                                                                   |           |                                                                                                  |
| 15:45 - 17:00 | [Critical evidence appraisal](https://drive.google.com/file/d/1L-VBrT149gh5ggYgvteQDfBbK4RrV9Sp/view?usp=share_link)                                                           | Practical | [Marybeth Maritim](https://cema-africa.uonbi.ac.ke/people/clinical-research/dr-marybeth-maritim) |

::: {.callout-note appearance="minimal"}
## Day 3: 24th July 2024

## Economic Evaluation in HTA

**Objective:** Understanding economic frameworks

**Session Chair:** [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech)
:::

| Time          | Topic                                                                                                                                              | Type      | Presenter                                                                             |
|-----------------|-----------------|-----------------|----------------------|
| 08:30 - 09:30 | [Evidence synthesis: Systematic reviews and meta-analysis](https://drive.google.com/file/d/1z2g2WlI4LzQDt-hsj-NvZrI0ZWfggA6J/view?usp=share_link)  | Lecture   | [George Paul Omondi](https://globalhealthcenter.umn.edu/staff/george-omondi-paul)     |
| 09:30 - 10:30 | [Overview of economic evaluation frameworks](https://drive.google.com/file/d/1fWHey22HVBsbeG4IFHoq3NPzRQu3lZDh/view?usp=share_link)                | Lecture   | [Manit Sittimart](https://www.hitap.net/en/staff/179664)                              |
| 10:30 - 11:00 | ☕ Tea break                                                                                                                                       |           |                                                                                       |
| 11:00 - 11:45 | [Concepts and applications of cost analysis in Health Care](https://drive.google.com/file/d/1pCyhpufkj1ejd7bIJAr0MIOrniwuKL2s/view?usp=share_link) | Lecture   | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech) |
| 11:45 - 12:45 | [Costing exercise](https://drive.google.com/file/d/1dqRuzosMXlk5XeB9n_AclezbFmNF-csr/view?usp=share_link)                                          | Practical | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech) |
| 13:00 - 14:00 | 🍲 Lunch break                                                                                                                                     |           |                                                                                       |
| 14:00 - 14:40 | [Health Outcome Assessment](https://drive.google.com/file/d/1Ghz7suAcQospw5V7aNd_MnvgH1W98YKE/view?usp=share_link)                                 | Lecture   | [Panchanok Muenkaew](https://www.hitap.net/en/staff/189371)                           |
| 14:40 - 15:10 | [Measuring outcomes](https://drive.google.com/file/d/1BR92jVn8MCRtZwj1a8VCB9hBJFZrxXty/view?usp=share_link)                                        | Practical | [Panchanok Muenkaew](https://www.hitap.net/en/staff/189371)                           |
| 15:10 - 15:30 | ☕ Tea break                                                                                                                                       |           |                                                                                       |
| 15:30 - 17:00 | [Topic prioritization](https://drive.google.com/file/d/1dC_fWXPPq4eJIwJkMTNpxjnbIzdl8kmr/view?usp=share_link)                                      | Practical | [Saudamini Dabak](https://www.hitap.net/en/staff/170776)                              |

::: {.callout-note appearance="minimal"}
## Day 4: 25th July 2024

## Economic Evaluation in HTA

**Objective:** Principles of economic evaluation in healthcare

**Session Chair:** [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech)
:::

| Time          | Topic                                                                          | Type      | Presenter                                                                             |
|-----------------|------------------|-----------------|--------------------|
| 08:30 - 09:05 | Economic modeling techniques I: Decision trees                                 | Lecture   | [Manit Sittimart](https://www.hitap.net/en/staff/179664)                              |
| 09:05 - 09:55 | Economic modeling techniques I: Decision trees                                 | Practical | [Manit Sittimart](https://www.hitap.net/en/staff/179664)                              |
| 09:55 - 10:20 | ☕ Tea break                                                                   |           |                                                                                       |
| 10:20 - 11:00 | Economic modeling techniques II: Markov models                                 | Lecture   | [Manit Sittimart](https://www.hitap.net/en/staff/179664)                              |
| 11:00 - 12:30 | Markov modelling                                                               | Practical | [Manit Sittimart](https://www.hitap.net/en/staff/179664)                              |
| 12:30 - 14:15 | 🍲 Lunch break                                                                 |           |                                                                                       |
| 14:15 - 14:45 | Uncertainty and interpretation                                                 | Lecture   | [Manit Sittimart](https://www.hitap.net/en/staff/179664)                              |
| 14:45 - 15:30 | Budget Impact analysis (BIA)                                                   | Lecture   | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech) |
| 15:30 - 15:45 | ☕ Tea break                                                                   |           |                                                                                       |
| 15:40 - 16:45 | Literature review and critical appraisal of health economic evaluation studies | Lecture   | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech) |
| 16:45 - 17:00 | Group feedback and Q&A session                                                 |           | All                                                                                   |

::: {.callout-note appearance="minimal"}
## Day 5: 26th July 2024

## Social and Equity considerations for HTA

**Objective:** Social ethics and equity in health technology assessment

**Session Chair:** [Jeanette Dawa](https://cema-africa.uonbi.ac.ke/people/secretariat/dr-jeanette-dawa)
:::

| Time          | Topic                                                                                               | Type    | Presenter                                                                               |
|-----------------|---------------------|-----------------|-----------------|
| 08:30 - 09:30 | Introduction to social, ethics and equity in HTA                                                    | Lecture | [Alex Nginyo](https://sep.kemri-wellcome.org/science-at-kemri/alex-hinga/)              |
| 09:30 - 10:30 | Social determinants of Health & Equity in Health                                                    | Lecture | [Alex Nginyo](https://sep.kemri-wellcome.org/science-at-kemri/alex-hinga/)              |
| 10:30 - 11:00 | ☕ Tea break                                                                                        |         |                                                                                         |
| 11:00 - 11:45 | Applying social, ethics and equity principles in HTA                                                | Lecture | [Saudamini Dabak](https://www.hitap.net/en/staff/170776)                                |
| 11:45 - 12:45 | National Health Policies and Strategies policies and their importance in healthcare decision-making | Lecture | [David Khaoya](http://www.healthpolicyplus.com/DKhaoya.cfm)                             |
| 13:00 - 14:00 | 🍲 Lunch break                                                                                      |         |                                                                                         |
| 14:00 - 15:00 | Course evaluation and feedback                                                                      |         | [Tabitha Okech](https://cema-africa.uonbi.ac.ke/people/epidemiology/dr-tabitha-okech)   |
| 15:00 -16:00  | Next steps and closing remarks                                                                      |         | [Thumbi Mwangi](https://cema-africa.uonbi.ac.ke/people/epidemiology/prof-thumbi-mwangi) |
| 15:30 - 16:00 | ☕ Tea break                                                                                        |         |                                                                                         |
